import { useState } from 'react';
import Head from 'next/head';
import Tile from '../components/Tile';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [cities, setCities] = useState(["Los Angeles", "New York", "Berlin", "Zurich", "Tokyo"]);
  const [userInputCity, setUserInputCity] = useState('');

  const handleInput = (event) => {
    setUserInputCity(event.target.value);
  }

  const onSubmit = () => {
    /**
     * Only update the list of cities displayed if the 
     * inputted city is not a duplicate.
     */
    if (cities.includes(userInputCity)) {
      setUserInputCity('');
    } else {
      setCities(prevCities => [...prevCities, userInputCity]);
      setUserInputCity('');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{`What's the Weather?`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/weather.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {`What's the Weather?`}
        </h1>

        <div className={`${styles.searchBox} ${styles.description}`}>
          <label htmlFor="input-location">
            Search Location:
          </label>

          <input
            type="text"
            id="input-location"
            placeholder={" example: London"}
            value={userInputCity}
            onChange={handleInput}
          />

          <button onClick={onSubmit}>
            Search
          </button>
        </div>

        <div className={styles.grid}>
          {cities.map((city, index) => {
            const cityUrl = `/${city.split(" ").join("-").toLowerCase()}`;
            return (<Tile location={city} key={index} href={cityUrl} />)
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/abirrer"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Anna Birrer
        </a>
      </footer>
    </div>
  )
}
