import Head from 'next/head';
import Tile from '../components/Tile';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`What's the Weather?`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/weather.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {`What's the Weather?`}
        </h1>

        <p className={styles.description}>
          Check the weather in your area!
        </p>

        <div className={styles.grid}>
          <Tile location='Your Location' temp={19} href={'/your-location'}/>
          <Tile location='Los Angeles' temp={27} href={'/los-angeles'}/>
          <Tile location='New York' temp={24} href={'/new-york'}/>
          <Tile location='Berlin' temp={20} href={'/berlin'}/>
          <Tile location='Zürich' temp={16} href={'/zuerich'}/>
          <Tile location='Tokyo' temp={39} href={'/tokyo'}/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/abirrer"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Anna Birrer
        </a>
      </footer>
    </div>
  )
}
